version: "3.7"

services:
  firebird:
    restart: always
    image: jacobalberty/firebird:latest
    container_name: firebird-db
    volumes:
      - ./db/firebird-banco:/var/lib
    ports:
      - 3050:3050
      - 3051:3051
    environment:
      TZ: America/Sao_Paulo
      ISC_PASSWORD: 123456
      FIREBIRD_PASSWORD: 123456
      FIREBIRD_DATABASE: desafio_db
    healthcheck:
      test: "exit 0"
    networks:
      - development-network

volumes:
  firebird-banco:

networks:
  development-network:
    driver: bridge