CREATE SEQUENCE sq_user
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE sq_customer
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE sq_order
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE sq_delivery
  START WITH 1
  INCREMENT BY 1;

INSERT INTO TB_USER
(ID, PASSWORD, ROLES, USERNAME)
VALUES(1, '$2a$12$v3H5wfMS5OxvrU3qveb6n.KCW2/gPX3o/mSA0pBznAB4Il0gwXwjC', 'ADMIN', 'admin');