EXECUTE BLOCK
AS
BEGIN
  EXECUTE STATEMENT 'CREATE SEQUENCE sq_user START WITH 1 INCREMENT BY 1';
  EXECUTE STATEMENT 'CREATE SEQUENCE sq_customer START WITH 1 INCREMENT BY 1';
  EXECUTE STATEMENT 'CREATE SEQUENCE sq_order START WITH 1 INCREMENT BY 1';
  EXECUTE STATEMENT 'CREATE SEQUENCE sq_delivery START WITH 1 INCREMENT BY 1';
END

